### ISSUE TITLE
I have a question about that if each variable has only 2 data, it will give all varibles the same independent contribution? 

### ISSUE THREAD

**Issue by EcoSummerCoder** [cjbwalsh/hier.part#1]
The code:
library(readxl)
library(vegan)
library(hier.part)
library(gtools)
library(rdaenvpart)

xs = c(2.01E+03,2.04E+03) 
xc = c(2.08e+03,2.05e+03)
xp = c(7.01e+01,1.42e+01)

step1 = rbind(xs,xc,xp)
xpc   = data.frame(xc,-xp)
res1  = hier.part(xs,xpc,family = 'gaussian',gof = "RMSPE", barplot = TRUE)

step1_xc_x = res1$I.perc$I[1]
step1_xp_x = res1$I.perc$I[2]
============
results are 50% for xp and xc

**Comment by cjbwalsh** [comment]
Hierarchical partitioning partitions variance explained by a linear statistical model.  Such models require more than two data to have any point (and usually the number of data should be at least ~10 times the number of predictor variables for adequate inference: see for instance Tabachnik and Fidell 2013 Using Multivariate Statistics)

**Comment by EcoSummerCoder** [comment]
Thanks for replying and solving my doubt.
